default:
  image: docker
  services:
  - docker:dind

stages:
  - release

release-job:
  stage: release
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE/guacd:git-$CI_COMMIT_SHORT_SHA .
    - docker push $CI_REGISTRY_IMAGE/guacd:git-$CI_COMMIT_SHORT_SHA 

